### ISSUE TITLE
 ## Broken test ##

### ISSUE THREAD

**Issue by alrawi90** [learn-co-curriculum/javascript-intro-to-mocha#10]
Hi,
**This lab has a broken test , here is the trace...**
 ##
`       at Mocha.loadFiles (/home/alideveloper90-29009/code/labs/javascript-intro-to-mocha-re-coded-000/node_modules/mocha/lib/mocha.js:217:14)          
    at Mocha.run (/home/alideveloper90-29009/code/labs/javascript-intro-to-mocha-re-coded-000/node_modules/mocha/lib/mocha.js:469:10)                
    at Object.<anonymous> (/home/alideveloper90-29009/code/labs/javascript-intro-to-mocha-re-coded-000/node_modules/mocha/bin/_mocha:404:18)         
    at Module._compile (module.js:570:32)                                                                                                            
    at Object.Module._extensions..js (module.js:579:10)                                                                                              
    at Module.load (module.js:487:32)                                                                                                                
    at tryModuleLoad (module.js:446:12)                                                                                                              
    at Function.Module._load (module.js:438:3)                                                                                                       
    at Module.runMain (module.js:604:10)                                                                                                             
    at run (bootstrap_node.js:394:7)                                                                                                                 
    at startup (bootstrap_node.js:149:9)                                                                                                             
    at bootstrap_node.js:509:3                                                                                                                       
npm ERR! Test failed.  See above for more details.                                                                                                   
  
`

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
